version: '3.0'

expectations:
  population_size: 500

actions:

  generate_measure_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2016-01-04 to 2021-01-10 by week"
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition
    needs: [generate_measure_cohort]
    outputs:
      moderately_sensitive:
        measure: output/measure_*_rate.csv

